version: "2.4"

services:
  drupal:
    ports:
      - "80:8080"
  # Removing traefik service functionality cause we don't need it during testing.
  # https://github.com/docker/compose/issues/3729
  traefik:
    image: hello-world

volumes:
  mariadb-data:
