variables:
  DOCKER_VERSION: "19.03.8"

test:
  image: registry.gitlab.com/nikathone/image-utils/docker:$DOCKER_VERSION-compose
  stage: test
  services:
    - docker:$DOCKER_VERSION-dind
  before_script:
    - docker --version && docker-compose --version
  script:
    - mv .github/docker-compose.override.yml docker-compose.override.yml
    - mv .github/.dockerignore .dockerignore
    - ls -all scripts/drupal/
    - echo "$HOME"
    - chmod +x scripts/drupal/init.sh
    - >
      docker image build
      --tag app-image-test:latest
      --target dev
      --build-arg code_dir=./codebase
      --build-arg base_image_tag=7.2.28-1.17.8-0ceedc1b
      --build-arg build_environment=dev
      --build-arg NGINX_LISTEN_PORT=8080
      --build-arg NGINX_SERVER_ROOT=/var/www/app/web
      --file drupal.Dockerfile
      .
    # - make
    # - >
    #   while ! docker container logs islandora_drupal_1 | grep "nginx entered RUNNING state"; do
    #     echo "Waiting for the site to be installed!"
    #     sleep 2m
    #   done
    # - curl -s http://localhost | grep '<h1 class="title page-title">Welcome to islandora</h1>'
  after_script:
    - echo "$(uname -s)"
    - if [[ -f /etc/os-release ]]; then cat /etc/os-release; fi
  only:
    refs:
      - master
      - development
