variables:
  DOCKER_VERSION: "19.03"

test:
  image: registry.gitlab.com/nikathone/image-utils/docker:$DOCKER_VERSION-compose
  stage: test
  services:
    - registry.gitlab.com/nikathone/image-utils/docker:$DOCKER_VERSION-dind
  before_script:
    - docker --version && docker-compose --version
  script:
    - |
      mv .github/docker-compose.override.yml docker-compose.override.yml
      mv .github/.dockerignore .dockerignore
      ./scripts/drupal/init.sh --codebase islandora
    - >
      docker image build
      --tag app-image-test:latest
      --target dev
      --build-arg code_dir=./codebase
      --build-arg base_image_tag=7.2.28-1.17.8-0ceedc1b
      --build-arg build_environment=dev
      --build-arg NGINX_LISTEN_PORT=8080
      --build-arg NGINX_SERVER_ROOT=/var/www/app/web
      --file drupal.Dockerfile
