version: "3.7"
services:
    drupal:
        # image:  ${REPOSITORY:-islandora}/composer:latest
        build:
          context: ./
          dockerfile: ${PROJECT_DRUPAL_DOCKERFILE:-./drupal.Dockerfile}
          # target: dev # this will come back in for multi-stage
          # args:
          #   - composer_project="drupal/recommended-project"
          #   - code_dir=./codebase
          #   - base_image_tag=latest
          #   - build_environment=dev
          #   - PHP_DATE_TIMEZONE=${PHP_DATE_TIMEZONE:-UTC}
          #   # XDEBUG confd build time args - you can set it to 0 turn it off.
          #   - PHP_XDEBUG=${PHP_XDEBUG:-1}
          #   - PHP_IDE_CONFIG="serverName=${PHP_IDE_CONFIG_SERVER_NAME:-drupal.localhost}"
          #   - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-host.docker.internal}
          #   - PHP_XDEBUG_DEFAULT_ENABLE=${PHP_XDEBUG_DEFAULT_ENABLE:-1}
          #   - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
          #   # NGINX confd build time args
          #   - NGINX_SERVER_ROOT=${APP_DOCROOT:-/var/www/app/web}
          #   - NGINX_LISTEN_PORT=8080
        restart: unless-stopped
        volumes:
          #- drupal-config-data:/var/www/drupal/config
          #- drupal-sites-data:/var/www/drupal/web/sites
          #- ./config/drupal/settings.php:/var/www/drupal/web/sites/default/settings.php
          - ./codebase:/var/www/drupal
          - ./config/drupal/settings.php.local:/var/www/drupal/web/sites/default/settings.php
          - ./config/drupal:/opt/drupal_config
          - ./scripts:/opt/scripts
          - solr-data:/opt/solr/server/solr
          - jwt-data:/opt/keys/claw/
        depends_on:
          - solr
          - fcrepo
          - database
          - activemq
        networks:
          default:
            aliases:
              - drupal.localhost
          external: # needed to run composer update
        labels:
          - traefik.http.services.drupal.loadbalancer.server.port=80
          - traefik.http.routers.drupal_http.service=drupal
          - traefik.http.routers.drupal_http.entrypoints=http
          - traefik.http.routers.drupal_http.rule=Host(`islandora.localhost`)

volumes:
  drupal-config-data:
  drupal-sites-data: