version: '3.7'

## ISLE 8 Draft Prototype
## January 22, 2020
## Release (Alpha) (0.0.1)

services:

  activemq:
    # review https://hub.docker.com/r/rmohr/activemq/
    image: rmohr/activemq:5.15.9
    container_name: isle-dc-activemq-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik     
    ports:
    # TO DO: Determine what ports should be exposed?  
      - "1883:1883"   #MQTT
      - "5672:5672"   #AMQP
      - "8161:8161"   #UI
      - "61613:61613" #STOMP
      - "61614:61614" #WS
      - "61616:61616" #JMS
    volumes:
      # TO DO: Determine correct settings of conf below
      - ./config/activemq/conf:/opt/activemq/conf
      - isle-dc-activemq-data:/opt/activemq/data
      # TO DO: Determine what type of container handling is needed
    restart: always


  drupal:
    # review https://github.com/docker-library/docs/blob/master/drupal/content.md
    image: drupal:8.8.1-apache
    container_name: isle-dc-drupal-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    ports:
      - 8080:80
    volumes:
      # TO DO: Determine what is Drupal volume setup?
        # Disagreement re volumes in Drupal community https://github.com/docker-library/drupal/issues/3
        # Is it an idea to only mount sites data and rebuild image with Drupal code changes ?
        # Volumes setup should be reviewed https://hub.docker.com/_/drupal/
      # TO DO: Determine what should be in config/drupal? .keep file is in place for now to allow empty dir to appear.  
      - ./data/drupal/modules:/var/www/html/modules
      - ./data/drupal/profiles:/var/www/html/profiles
      - ./data/drupal/sites:/var/www/html/sites
      - ./data/drupal/themes:/var/www/html/themes
      # TO DO: Determine what type of container handling is needed
    restart: always
  
 
  isle-blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: isle-dc-blazegraph-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=4096M
      - JAVA_MIN_MEM=1024M
    env_file:
      - .env
    networks:
      - isle-internal
    depends_on:
      - fedora
      - traefik
    ports:
      - "8889:8080"
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - config/blazegraph/RWStore.properties:/RWStore.properties
      - ./data/blazegraph/data:/data
    # TO DO: Determine what type of container handling is needed
    restart: always


  cantaloupe:
    image: lyrasis/cantaloupe:4.0-1
    container_name: isle-dc-cantaloupe-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=2048M
      - JAVA_MIN_MEM=512M  
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - fedora
      - traefik
    ports:
      - ##:##
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?  
      - ./config/cantaloupe/cantaloupe.properties:/usr/local/cantaloupe/cantaloupe.properties
      - ./config/cantaloupe/delegates.rb:/usr/local/cantaloupe/delegates.rb
    # TO DO: Determine what type of container handling is needed
    restart: always





networks:
  isle-dc-internal:
  isle-dc-external:


volumes:
  isle-dc-activemq-data: