version: "3.7"
networks:
  default:
    internal: true
volumes:
  mariadb-data:
  mariadb-files:
services:
  # Database is chosen as the service name rather than mariadb,
  # as institutions may want to swap out back-ends later and
  # database is a more sensible default. When we have other
  # databases the user can choose the appropriate docker-compose.yml
  # file to use or none at all if using some database as a service.
  database:
    image: ${REPOSITORY:-islandora}/mariadb:${TAG:-latest}
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-files:/var/lib/mysql-files
    labels:
      - traefik.enable=true
      - traefik.tcp.services.${COMPOSE_PROJECT_NAME-isle-dc}-database.loadbalancer.server.port=3306
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-database_tcp.service=${COMPOSE_PROJECT_NAME-isle-dc}-database
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-database_tcp.entrypoints=database
      - traefik.tcp.routers.${COMPOSE_PROJECT_NAME-isle-dc}-database_tcp.rule=HostSNI(`*`)
    networks:
      default:
        # Allow drupal to access the database with it's edge name to reference
        # this service in addition to `database`. This allows us to use the edge
        # name in settings.php so Drush on the host machine can be used in the
        # codebase folder.
        aliases:
            - database-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}
            - database-${COMPOSE_PROJECT_NAME-isle-dc}-${DRUPAL_SITE_HOST-traefik.me}
      gateway:
