version: '3.7'

## ISLE 8 Draft Prototype
## January 22, 2020
## Release (Alpha) (0.0.1)

services:


  traefik:
    # review https://hub.docker.com/_/traefik
    image: traefik:2.1.3
    container_name: isle-dc-traefik-${CONTAINER_SHORT_ID}
    networks:
      isle-internal:
      isle-external:
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
      - /var/run/docker.sock:/var/run/docker.sock
      # SSL Choice 1: To use Let's Encrypt for SSL- uncomment ONLY the line below and then create an empty config/proxy/acme.json file
      # - ./config/proxy/acme.json:/acme.json
      # SSL Choice 2: To use commercial SSLs - uncomment ONLY the line below. Add your SSL certs (.cert, .pem, .key) files to config/proxy/ssl-certs
      # - ./config/proxy/ssl-certs:/certs:ro
      # Based on the choice of SSL type made above, you'll need to refer to this /config/proxy/traefik.production.toml file for further configuration instructions.
      - ./config/proxy/traefik.production.toml:/etc/traefik/traefik.toml
    # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
    labels:
      - traefik.port=8080
      ## Enabling access to the Traefik interface is not safe in a production environment unless you have the ISLE system behind a firewall and only ports 80 and 443 exposed.
      - traefik.enable=false
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};


  activemq:
    # review https://hub.docker.com/r/rmohr/activemq/
    image: rmohr/activemq:5.15.9
    container_name: isle-dc-activemq-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik     
    ports:
    # TO DO: Determine what ports should be exposed?  
      - "1883:1883"   #MQTT
      - "5672:5672"   #AMQP
      - "8161:8161"   #UI
      - "61613:61613" #STOMP
      - "61614:61614" #WS
      - "61616:61616" #JMS
    volumes:
      # TO DO: Determine correct settings of conf below
      - ./config/activemq/conf:/opt/activemq/conf
      - isle-dc-activemq-data:/opt/activemq/data
      # TO DO: Determine what type of container handling is needed
    restart: always


  drupal:
    # review https://github.com/docker-library/docs/blob/master/drupal/content.md
    image: drupal:8.8.1-apache
    container_name: isle-dc-drupal-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - mysql
      - fcrepo
      - solr
      - traefik
    ports:
      - 8080:80
    volumes:
      # TO DO: Determine what is Drupal volume setup?
        # Disagreement re volumes in Drupal community https://github.com/docker-library/drupal/issues/3
        # Is it an idea to only mount sites data and rebuild image with Drupal code changes ?
        # Volumes setup should be reviewed https://hub.docker.com/_/drupal/
      # TO DO: Determine what should be in config/drupal? .keep file is in place for now to allow empty dir to appear.  
      - ./data/drupal/modules:/var/www/html/modules
      - ./data/drupal/profiles:/var/www/html/profiles
      - ./data/drupal/sites:/var/www/html/sites
      - ./data/drupal/themes:/var/www/html/themes
      # TO DO: Determine what type of container handling is needed
    restart: always
  
 
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: isle-dc-blazegraph-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=4096M
      - JAVA_MIN_MEM=1024M
    env_file:
      - .env
    networks:
      - isle-internal
    depends_on:
      - fcrepo
      - traefik
    ports:
      - "8889:8080"
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - config/blazegraph/RWStore.properties:/RWStore.properties
      - ./data/blazegraph/data:/data
    # TO DO: Determine what type of container handling is needed
    restart: always


  cantaloupe:
    image: lyrasis/cantaloupe:4.0-1
    container_name: isle-dc-cantaloupe-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=2048M
      - JAVA_MIN_MEM=512M  
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - fcrepo
      - traefik
    ports:
      - ##:##
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?  
      - ./config/cantaloupe/cantaloupe.properties:/usr/local/cantaloupe/cantaloupe.properties
      - ./config/cantaloupe/delegates.rb:/usr/local/cantaloupe/delegates.rb
    # TO DO: Determine what type of container handling is needed
    restart: always


  fcrepo:
    # TO DO: We will need to build this image using elements from the Ansible playbook & https://github.com/fcrepo4-labs/fcrepo4-docker
    image: islandorafoundation/fcrepo:5.1.0
    container_name: isle-dc-fcrepo-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - mysql
      - solr
      - traefik
    ports:
      - 8081:8080
    volumes:
    # TO DO: Determine if further bindmounts / config files are needed to tune Fedora
      - ./data/fedora/datastreamStore:/usr/local/fedora/data/datastreamStore
      - ./data/fedora/objectStore:/usr/local/fedora/data/objectStore
      - isle-fedora-resourceIndex:/usr/local/fedora/data/resourceIndex
    # TO DO: Should this be a bind mount / config instead?  
      - isle-fedora-XACML:/usr/local/fedora/data/fedora-xacml-policies
    # TO DO: Determine what type of container handling is needed
    restart: always


  mysql:
    ## Using for Protoype
    image: mysql:5.7
    container_name: isle-dc-mysql-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-internal
    depends_on:
      - traefik
    ports:
      - "3306:3306"
    volumes:
    ## TO DO: How to allow for slow query log setup?
    ## Customization: Allows for additional tuning of MySQL.
    ## From ISLE 7 work: keeping MySQL in a Docker volume avoids a slew of issues from bind-mounting
      - ./config/mysql/ISLE.cnf:/etc/mysql/mysql.conf.d/ISLE.cnf
      - isle-db-data:/var/lib/mysql






networks:
  isle-dc-internal:
  isle-dc-external:


volumes:
  isle-dc-activemq-data: