version: '3.7'

## ISLE 8 Draft Prototype
## Feb, 2020
## MVP 1 - Traefik, Solr, MySQL & Drupal (using Woodby images for Apache, Drupal and Solr)

services:

  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: isle-dc-apache-${PROJECT_SHORT_ID}
    depends_on:
      - php
      - traefik
      - mysql
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/web
    volumes:
      - ./codebase:/var/www/html
## For macOS users (https://wodby.com/docs/stacks/drupal/local#docker-for-mac)
##      - ./codebase:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"

 
## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and as an conditional either mysql or postgres
  mysql:
    ## Using for protoype database
    image: mysql:5.7
    container_name: isle-dc-mysql-${PROJECT_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik
    ports:
      - "3306:3306"
    volumes:
    ## TO DO: How to allow for slow query log setup?
    ## Customization: Allows for additional tuning of MySQL.
    ## From ISLE 7 work: keeping MySQL in a Docker volume avoids a slew of issues from bind-mounting
      - ./config/mysql/isle-mysql.cnf:/etc/mysql/mysql.conf.d/isle-mysql.cnf
      - isle-dc-mysql-data:/var/lib/mysql

  mariadb:
    ## Using for protoype database
    image: wodby/mariadb:$MARIADB_TAG
    container_name: isle-dc-mysql-${PROJECT_SHORT_ID}
    env_file:
      - .env
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
    ## TO DO: How to allow for slow query log setup?
    ## Customization: Allows for additional tuning of MySQL.
    ## From ISLE 7 work: keeping MySQL in a Docker volume avoids a slew of issues from bind-mounting
      - ./config/mysql/isle-mysql.cnf:/etc/mysql/mysql.conf.d/isle-mysql.cnf
    # - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - isle-dc-mariadb-data:/var/lib/mysql




  solr:
    image: wodby/solr:$SOLR_TAG
    container_name: isle-dc-solr-${PROJECT_SHORT_ID}
    environment:
      - SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
      - SOLR_HEAP: 1024m
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik  
    ports:
      - "8082:8080"
    volumes:
      - isle-dc-solr-data:/usr/local/solr
    # TO DO: Determine what type of container handling is needed
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"    
    restart: always


  traefik:
    # review https://hub.docker.com/_/traefik
    image: traefik:2.1.3
    container_name: isle-dc-traefik-${PROJECT_SHORT_ID}
    networks:
      isle-dc-internal:
      isle-dc-external:
    env_file:
      - .env
    ports:
      - "80:80"
      #- "443:443"
      #- "8080:8080"
    volumes:
      # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
      - /var/run/docker.sock:/var/run/docker.sock
      # SSL Choice 1: To use Let's Encrypt for SSL- uncomment ONLY the line below and then create an empty config/traefik/acme.json file
      # - ./config/traefik/acme.json:/acme.json
      # SSL Choice 2: To use commercial SSLs - uncomment ONLY the line below. Add your SSL certs (.cert, .pem, .key) files to config/traefik/ssl-certs
      # - ./config/traefik/ssl-certs:/certs:ro

      # Use Environment vaiables to pass in Traefik config; no traefik.yml required
      # by providers
      # Alternative to a static configureation /etc/traefik/traefik.yml"
      # Pass in config via flags or environment variables
      # https://docs.traefik.io/getting-started/configuration-overview
      # Obsolete - "./config/traefik/traefik.local.yml:/etc/traefik/traefik.yml"


networks:
  isle-dc-internal:
  isle-dc-external:


volumes:
  isle-dc-mariadb-data:
  isle-dc-solr-data:
  # isle-dc-postgres-data # Added to prototype but not currently used    