version: '3.7'

## ISLE 8 Draft Prototype
## January 22, 2020
## Release (Alpha) (0.0.1)

services:

  activemq:
    # review https://hub.docker.com/r/rmohr/activemq/
    image: rmohr/activemq:5.15.9
    container_name: isle-dc-activemq-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    ports:
      - "1883:1883"   #MQTT
      - "5672:5672"   #AMQP
      - "8161:8161"   #UI
      - "61613:61613" #STOMP
      - "61614:61614" #WS
      - "61616:61616" #JMS
    volumes:
      - ./config/activemq/conf:/opt/activemq/conf
      - isle-dc-activemq-data:/opt/activemq/data

  drupal:
    # review https://github.com/docker-library/docs/blob/master/drupal/content.md
    image: drupal:8.8.1-apache
    container_name: isle-dc-drupal-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - mysql
      - fedora
      - solr
      - traefik
    ports:
      - 8080:80
    volumes:
      # Disagreement with volumes in Drupal community https://github.com/docker-library/drupal/issues/3
      # idea to only mount sites data and rebuild image with Drupal code changes ?
      - ./data/drupal:/var/www/html/sites
    restart: always

-e MYSQL_DATABASE=drupal \
	-e MYSQL_USER=user \
	-e MYSQL_PASSWORD=password \
	-e MYSQL_ROOT_PASSWORD=password \

networks:
  isle-dc-internal:
  isle-dc-external:


volumes:
  isle-dc-activemq-data: