version: '3.7'

## ISLE 8 Draft Prototype
## January 22, 2020
## Release (Alpha) (0.0.1)

services:


  traefik:
    # review https://hub.docker.com/_/traefik
    image: traefik:2.1.3
    container_name: isle-dc-traefik-${CONTAINER_SHORT_ID}
    networks:
      isle-dc-internal:
      isle-dc-external:
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
      #- "8080:8080"
    volumes:
      # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
      - /var/run/docker.sock:/var/run/docker.sock
      # SSL Choice 1: To use Let's Encrypt for SSL- uncomment ONLY the line below and then create an empty config/traefik/acme.json file
      # - ./config/traefik/acme.json:/acme.json
      # SSL Choice 2: To use commercial SSLs - uncomment ONLY the line below. Add your SSL certs (.cert, .pem, .key) files to config/traefik/ssl-certs
      # - ./config/traefik/ssl-certs:/certs:ro
      # TO DO: Determine if toml files are still to be bound in Traefik 2.0
    # TO DO: Update according to new Traefik 2.0 conventions (values below based on 1.7.9, are incomplete & wrong due to missing "routing" labels)
    labels:
      - traefik.port=8080
      ## Enabling access to the Traefik interface is not safe in a production environment unless you have the ISLE system behind a firewall and only ports 80 and 443 exposed.
      - traefik.enable=false
      - traefik.frontend.rule=Host:admin.${BASE_DOMAIN};


  activemq:
    # review https://hub.docker.com/r/rmohr/activemq/
    image: rmohr/activemq:5.15.9
    container_name: isle-dc-activemq-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik     
    ports:
    # TO DO: Determine what ports should be exposed?  
      - "1883:1883"   #MQTT
      - "5672:5672"   #AMQP
      - "8161:8161"   #UI
      - "61613:61613" #STOMP
      - "61614:61614" #WS
      - "61616:61616" #JMS
    volumes:
      # TO DO: Determine correct settings of conf below
      - ./config/activemq/conf:/opt/activemq/conf
      - isle-dc-activemq-data:/opt/activemq/data
      # TO DO: Determine what type of container handling is needed
    restart: always


  drupal:
    # review https://github.com/docker-library/docs/blob/master/drupal/content.md
    image: drupal:8.8.1-apache
    container_name: isle-dc-drupal-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - mysql
      - traefik
    ports:
      - 8080:80
    volumes:
      # TO DO: Determine what is Drupal volume setup?
        # Disagreement re volumes in Drupal community https://github.com/docker-library/drupal/issues/3
        # Is it an idea to only mount sites data and rebuild image with Drupal code changes ?
        # Volumes setup should be reviewed https://hub.docker.com/_/drupal/
      # TO DO: Determine what should be in config/drupal? .keep file is in place for now to allow empty dir to appear.  
      - ./data/drupal/modules:/var/www/html/modules
      - ./data/drupal/profiles:/var/www/html/profiles
      - ./data/drupal/sites:/var/www/html/sites
      - ./data/drupal/themes:/var/www/html/themes
      # TO DO: Determine what type of container handling is needed
    restart: always
  
 
  blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: isle-dc-blazegraph-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=4096M
      - JAVA_MIN_MEM=1024M
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - fcrepo
      - traefik
    ports:
      - "8889:8080"
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/blazegraph/RWStore.properties:/RWStore.properties
      - ./data/blazegraph/data:/data
    # TO DO: Determine what type of container handling is needed
    restart: always


  cantaloupe:
    image: lyrasis/cantaloupe:4.0-1
    container_name: isle-dc-cantaloupe-${CONTAINER_SHORT_ID}
    environment:
      # TO DO: Detemine Java memory needs
      - JAVA_MAX_MEM=2048M
      - JAVA_MIN_MEM=512M  
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik
    ports:
      - ##:##
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
    # TO DO: Determine what is to be done about /cantaloupe/cache settings and storage?
      - ./config/cantaloupe/cantaloupe.properties:/usr/local/cantaloupe/cantaloupe.properties
      - ./config/cantaloupe/delegates.rb:/usr/local/cantaloupe/delegates.rb
    # TO DO: Determine what type of container handling is needed
    restart: always

## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and as an optional service
  fcrepo:
    # TO DO: We will need to build this image using elements from the Ansible playbook & https://github.com/fcrepo4-labs/fcrepo4-docker
    image: islandoradevops/fcrepo:5.1.0
    container_name: isle-dc-fcrepo-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - mysql
      - traefik
    ports:
      - 8081:8080
    volumes:
    # TO DO: Determine if further bindmounts / config files are needed to tune Fedora
      - ./data/fcrepo/datastreamStore:/usr/local/fedora/data/datastreamStore
      - ./data/fcrepo/objectStore:/usr/local/fedora/data/objectStore
      - isle-dc-fcrepo-resourceIndex:/usr/local/fedora/data/resourceIndex
    # TO DO: Should this be a bind mount / config instead?  
      - isle-dc-fcrepo-XACML:/usr/local/fedora/data/fedora-xacml-policies
    # TO DO: Determine what type of container handling is needed
    restart: always

## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and as an conditional either mysql or postgres
  mysql:
    ## Using for protoype database
    image: mysql:5.7
    container_name: isle-dc-mysql-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik
    ports:
      - "3306:3306"
    volumes:
    ## TO DO: How to allow for slow query log setup?
    ## Customization: Allows for additional tuning of MySQL.
    ## From ISLE 7 work: keeping MySQL in a Docker volume avoids a slew of issues from bind-mounting
      - ./config/mysql/ISLE.cnf:/etc/mysql/mysql.conf.d/isle-mysql.cnf
      - isle-dc-mysql-data:/var/lib/mysql


## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and as an conditional either mysql or postgres 
# TO DO" Phase III+ after prototype build, test and use but matomo expects mysql
#  postgres:
#    # review https://hub.docker.com/_/postgres
#    image: postgres:12.1
#    container_name: isle-dc-postgres-${CONTAINER_SHORT_ID}
#    env_file:
#      - .env
#    networks:
#      - isle-dc-internal
#    depends_on:
#      - traefik
#    ports:
#      - 8082:8080
#    volumes:
#    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
#      - ./config/postgres/isle-postgres.cnf:/etc/postgresql/postgresql.conf
#      - isle-dc-postgres-data:/var/lib/postgresql/data
#    # TO DO: Determine what type of container handling is needed
#    restart: always


  solr:
    image: solr/solr:8.4.1
    container_name: isle-dc-solr-${CONTAINER_SHORT_ID}
    environment:
      - JAVA_MAX_MEM=2048M
      - JAVA_MIN_MEM=512M
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - traefik  
    ports:
      - "8082:8080"
    volumes:
      - isle-dc-solr-data:/usr/local/solr
    # TO DO: Determine what type of container handling is needed
    restart: always

## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and as an optional service
  matomo:
    # https://github.com/matomo-org/docker 
    # TO DO: Use Apache or Nginx?
    image: matomo/matomo:3.13.1-apache
    container_name: isle-dc-matomo-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - drupal
      - traefik
    ports:
      - ##:##
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/matomo:/path_on_container
      - isle-dc-matomo-data:/var/www/html
    # TO DO: Determine what type of container handling is needed
    restart: always


## TO DO: Break this section out into another Docker-compose for extension https://docs.docker.com/compose/extends/ and clarity

### Microservices Connectors

  fits-connector: 
    image: islandoradevops/karaf-camel:1.0
    container_name: isle-dc-fits-connector-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - fits
      - traefik
    ports:
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/connectors/fits-connector/karaf_route.xml:/path_on_fits-connector_container/karaf_route.xml
    # TO DO: Determine what type of container handling is needed
    restart: always


  houdini-connector: 
    image: islandoradevops/karaf-camel:1.0
    container_name: isle-dc-houdini-connector-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - houdini
      - traefik
    ports:
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/connectors/houdini-connector/karaf_route.xml:/path_on_houdini-connector_container/karaf_route.xml
    # TO DO: Determine what type of container handling is needed
    restart: always


  homarus-connector: 
    image: islandoradevops/karaf-camel:1.0
    container_name: isle-dc-homarus-connector-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - homarus
      - traefik
    ports:
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/connectors/homarus-connector/homarus_route.xml:/path_on_homarus-connector_container/homarus_route.xml
    # TO DO: Determine what type of container handling is needed
    restart: always


  hypercube-connector: 
    image: islandoradevops/karaf-camel:1.0
    container_name: isle-dc-hypercube-connector-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - hypercube
      - traefik
    ports:
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/connectors/hypercube-connector/hypercube_route.xml:/path_on_hypercube-connector_container/hypercube_route.xml
    # TO DO: Determine what type of container handling is needed
    restart: always


  milliner-connector: 
    image: islandoradevops/karaf-camel:1.0
    container_name: isle-dc-milliner-connector-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - milliner
      - traefik
    ports:
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/connectors/milliner-connector/milliner_route.xml:/path_on_milliner-connector_container/milliner_route.xml
    # TO DO: Determine what type of container handling is needed
    restart: always


### Microservices 

  fits: 
    # https://github.com/harvard-lts/FITSServlet_Container
    image: harvardlts/fitsservlet_container:1.5.0
    container_name: isle-dc-fits-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
    ports:
      - :8080 #TO DO: What ports should be used here? What is dashboard port? given it exposes 8080, 8009 (ajp?) and 8443 (not used in backend)
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/fits:/path_on_fits_container
    # TO DO: Determine what type of container handling is needed
    restart: always


  houdini: 
    image: islandoradevops/houdini:1.0
    container_name: isle-dc-houdini-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?    
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/houdini/:/path_on__houdini_container
    # TO DO: Determine what type of container handling is needed
    restart: always


  homarus: 
    image: islandoradevops/homarus:1.0
    container_name: isle-dc-homarus-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?    
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/homarus/:/path_on__homarus_container
    # TO DO: Determine what type of container handling is needed
    restart: always


  hypercube: 
    image: islandoradevops/hypercube:1.0
    container_name: isle-dc-hypercube-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?    
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/hypercube/:/path_on__hypercube_container
    # TO DO: Determine what type of container handling is needed
    restart: always


  milliner: 
    image: islandoradevops/milliner:1.0
    container_name: isle-dc-milliner-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?    
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/milliner/:/path_on__milliner_container
    # TO DO: Determine what type of container handling is needed
    restart: always


  gemini: 
    image: islandoradevops/gemini:1.0
    container_name: isle-dc-gemini-${CONTAINER_SHORT_ID}
    env_file:
      - .env
    networks:
      - isle-dc-internal
    depends_on:
      - activemq
      - traefik
      - :8101 # TO DO: What ports should be used here? - Don't think they need to be exposed to the world?    
    volumes:
    # TO DO: Determine if this needs to be bind mounted or a Docker volume?
      - ./config/gemini/:/path_on__gemini_container
    # TO DO: Determine what type of container handling is needed
    restart: always



networks:
  isle-dc-internal:
  isle-dc-external:


volumes:
  isle-dc-activemq-data:
  isle-dc-fcrepo-resourceIndex:
  isle-dc-fcrepo-XACML:
  isle-dc-mysql-data:
  # isle-dc-postgres-data # Added to prototype but not currently used
  isle-dc-solr-data:
  isle-dc-matomo-data: