version: "3.7"
services:
  drupal:
    image:  ${REPOSITORY:-islandora}/sandbox:latest
    restart: unless-stopped
    volumes:
      - drupal-config-data:/var/www/drupal/config
      - drupal-sites-data:/var/www/drupal/web/sites
      - solr-data:/opt/solr/server/solr
    depends_on:
      - solr
      - fcrepo
      - database
      - activemq
    labels:
      - traefik.http.services.drupal.loadbalancer.server.port=80
      - traefik.http.routers.drupal_http.service=drupal
      - traefik.http.routers.drupal_http.entrypoints=http
      - traefik.http.routers.drupal_http.rule=Host(`islandora.localhost`)

volumes:
  drupal-config-data:
  drupal-sites-data: