version: "3.7"
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
services:
  homarus:
    image: ${REPOSITORY:-islandora}/homarus:${TAG:-latest}
  houdini:
    image: ${REPOSITORY:-islandora}/houdini:${TAG:-latest}
  hypercube:
    image: ${REPOSITORY:-islandora}/hypercube:${TAG:-latest}
  milliner:
    image: ${REPOSITORY:-islandora}/milliner:${TAG:-latest}
    networks:
      default:
      gateway:
  recast:
    image: ${REPOSITORY:-islandora}/recast:${TAG:-latest}
